<a href="https://colab.research.google.com/github/MfmRifath/TesorflowCourseDeepLearning/blob/main/00_tensorflow_fundemental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In This notebook we are going to cover some of the fundamental concepts of the tensor usnoing Tensorflow
More sepciallty we are gointo cover:
  * introductions to tensors
  * Getting informations from Tensors
  * Manipulating Tensors
  * Tensors and NumPy
  * Using @tf.function (a way to speed up your regular Python Funtions)
  * Using GPUs with Tensorflow (or TPUs)
  * Exsercise

#introduction to Tensors

In [1]:
#import Tesorflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [4]:
# create tensor with tf.constent()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dementions of a tensor (ndim stands for number os demenstions)
scalar.ndim

0

In [6]:
# create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#check the daimentions of the vector
vector.ndim

1

In [8]:
#Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [13]:
# Create tensors
tensor = tf.constant([[[1,2],
                      [3,4],
                      [4,5]],[[5,6],
                              [6,7],
                              [7,8]]])

tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [6, 7],
        [7, 8]]], dtype=int32)>

In [14]:
tensor.ndim

3

# what we've created so far:
* scalar: single Number
* Vector: Number with direction (e.g. wind epped and direction)
* Matrix : 2-dimentional aray of numbers
* Tensor: n-dementions of array