<a href="https://colab.research.google.com/github/MfmRifath/TesorflowCourseDeepLearning/blob/main/00_tensorflow_fundemental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In This notebook we are going to cover some of the fundamental concepts of the tensor usnoing Tensorflow
More sepciallty we are gointo cover:
  * introductions to tensors
  * Getting informations from Tensors
  * Manipulating Tensors
  * Tensors and NumPy
  * Using @tf.function (a way to speed up your regular Python Funtions)
  * Using GPUs with Tensorflow (or TPUs)
  * Exsercise

#introduction to Tensors

In [1]:
#import Tesorflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# create tensor with tf.constent()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dementions of a tensor (ndim stands for number os demenstions)
scalar.ndim

0

In [4]:
# create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the daimentions of the vector
vector.ndim

1

In [6]:
#Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Create tensors
tensor = tf.constant([[[1,2],
                      [3,4],
                      [4,5]],[[5,6],
                              [6,7],
                              [7,8]]])

tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [4, 5]],

       [[5, 6],
        [6, 7],
        [7, 8]]], dtype=int32)>

In [11]:
tensor.ndim

3

# what we've created so far:
* scalar: single Number
* Vector: Number with direction (e.g. wind epped and direction)
* Matrix : 2-dimentional aray of numbers
* Tensor: n-dementions of array

# Creating Tensors with tf.variable

In [12]:
#Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#Let's try change one of the element in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# let's try change our unchangable variable
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Rarely in practice will you need to decide whether to use tf.contant() or tf.variable to create tensors as Tensorflow does this for you. However if in doubt, use tf.contant() and chabged it later if needed.

#Creating Random Tensors

Random Tensors are Tensors of some arbitary size which contain Randon Numbers

In [17]:
# Create two random but (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for producibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the Order of elements in a tensor

In [20]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent orderd doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                             [3,4],
                             [2,5]])
#shuffle  our non-shuffeled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [31]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operation level random seed


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>